---
- name: This is a hello-world example
  hosts: default
  tasks:
    - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
      copy:
        content: hello world
        dest: /tmp/asnibletest.txt